export const questions = {
  1: {
    questionId: 1,
    questionText: 'How are you feeling today?',
    answerType: 'smilies',
    radioOptions: ['😞', '🙁', '😐', '🙂', '😃'],
  },
  2: {
    questionId: 2,
    questionText: "I am feeling ",
    boldText: "worried",
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
  },
  3: {
    questionId: 3,
    questionText: 'I am feeling',
    boldText: " enthusiastic",
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  4: {
    questionId: 4,
    questionText: 'I am feeling',
    boldText: " nervous",
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  5: {
    questionId: 5,
    questionText: 'I am feeling ',
    boldText: "curious/interested",
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  6: {
    questionId: 6,
    questionText: 'I am feeling ',
    boldText: "miserable",
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  7: {
    questionId: 7,
    questionText: 'I am feeling',
    boldText: " relaxed",
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  8: {
    questionId: 8,
    questionText: 'During the past week, I have been feeling ',
    boldText: "competent",
    answerType: 'radios',
    radioOptions: ['Never', 'Rarely', 'Regularly', 'Every day'],
    },
  9: {
    questionId: 9,
    questionText: 'During the past week, I have been feeling ',
    boldText: "sad",
    answerType: 'radios',
    radioOptions: ['Never', 'Rarely', 'Regularly', 'Every day'],
    },
  10: {
    questionId: 10,
    questionText: 'During the past week, I have been feeling ',
    boldText: "lonely",
    answerType: 'radios',
    radioOptions: ['Never', 'Rarely', 'Regularly', 'Every day'],
    },
  11: {
    questionId: 11,
    questionText: 'During the past week, I have been feeling ',
    boldText: "nauseous/seasick",
    answerType: 'radios',
    radioOptions: ['Never', 'Rarely', 'Regularly', 'Every day'],
    },
  12: {
    questionId: 12,
    questionText: 'During the past week, I have been feeling ',
    boldText: "inspired",
    answerType: 'radios',
    radioOptions: ['Never', 'Rarely', 'Regularly', 'Every day'],
    },
  13: {
    questionId: 13,
    questionText: 'During the past week, I have been feeling ',
    boldText: "happy",
    answerType: 'radios',
    radioOptions: ['Never', 'Rarely', 'Regularly', 'Every day'],
    },
  14: {
    questionId: 14,
    questionText: 'During the past week, I have been feeling ',
    boldText: "fatigued",
    answerType: 'radios',
    radioOptions: ['Never', 'Rarely', 'Regularly', 'Every day'],
    },
  15: {
    questionId: 15,
    questionText: 'During the past week, I have been feeling ',
    boldText: "angry/frustrated",
    answerType: 'radios',
    radioOptions: ['Never', 'Rarely', 'Regularly', 'Every day'],
    },
  16: {
    questionId: 16,
    questionText: 'During the past week, I have been feeling ',
    boldText: "relieved",
    answerType: 'radios',
    radioOptions: ['Never', 'Rarely', 'Regularly', 'Every day'],
    },
  17: {
    questionId: 17,
    questionText: 'Dear cadet, you are about to embark on your internship! Thank you for taking a few minutes to answer the following questions.',
    answerType: 'radios',
    radioOptions: [],
    },
  18: {
    questionId: 18,
    questionText: 'Thank you for sharing how you feel. A few more items to go…',
    answerType: 'radios',
    radioOptions: [],
    },
  19: {
    questionId: 19,
    questionText: 'I feel positive about my team',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  20: {
    questionId: 20,
    questionText: 'Having no internet on board makes me feel anxious',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  21: {
    questionId: 21,
    questionText: 'I am happy with my coach',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  22: {
    questionId: 22,
    questionText: 'I am sure I will make new friends',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  23: {
    questionId: 23,
    questionText: 'I would prefer to stay home',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  24: {
    questionId: 24,
    questionText: 'My luggage is packed and ready to go',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  25: {
    questionId: 25,
    questionText: 'When I need help I can count on my team',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  26: {
    questionId: 26,
    questionText: 'I am learning new things',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  27: {
    questionId: 27,
    questionText: 'I feel connected with people who care about me',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  28: {
    questionId: 28,
    questionText: 'Our coach treats us fairly',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  29: {
    questionId: 29,
    questionText: 'Having no internet access is very difficult',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  30: {
    questionId: 30,
    questionText: 'I don\'t know what is expected of me',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  31: {
    questionId: 31,
    questionText: 'Would you like to share anything else?',
    answerType: 'text',
    },
  32: {
    questionId: 32,
    questionText: 'I enjoy being at sea',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  33: {
    questionId: 33,
    questionText: 'I feel excluded from the group I want to belong to',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  34: {
    questionId: 34,
    questionText: 'There is nothing fun to do',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  35: {
    questionId: 35,
    questionText: 'My coach is open and easy to talk to',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  36: {
    questionId: 36,
    questionText: 'I help others in my team',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  37: {
    questionId: 37,
    questionText: 'In my free time, I mostly sleep',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  38: {
    questionId: 38,
    questionText: 'I am excited about the things I am learning',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  39: {
    questionId: 39,
    questionText: 'During the port stay, I was feeling ',
    boldText: "excited",
    answerType: 'radios',
    radioOptions: ['Never', 'Rarely', 'Regularly', 'Every day'],
    },
  40: {
    questionId: 40,
    questionText: 'During the port stay, I was feeling ',
    boldText: "sad",
    answerType: 'radios',
    radioOptions: ['Never', 'Rarely', 'Regularly', 'Every day'],
    },
  41: {
    questionId: 41,
    questionText: 'During the port stay, I was feeling ',
    boldText: "angry/frustrated",
    answerType: 'radios',
    radioOptions: ['Never', 'Rarely', 'Regularly', 'Every day'],
    },
  42: {
    questionId: 42,
    questionText: 'During the port stay, I was feeling ',
    boldText: "confident",
    answerType: 'radios',
    radioOptions: ['Never', 'Rarely', 'Regularly', 'Every day'],
    },
  43: {
    questionId: 43,
    questionText: 'During the port stay, I was feeling ',
    boldText: "lonely",
    answerType: 'radios',
    radioOptions: ['Never', 'Rarely', 'Regularly', 'Every day'],
    },
  44: {
    questionId: 44,
    questionText: 'During the port stay, I was feeling ',
    boldText: "fatigued",
    answerType: 'radios',
    radioOptions: ['Never', 'Rarely', 'Regularly', 'Every day'],
    },
  45: {
    questionId: 45,
    questionText: 'During the port stay, I was feeling ',
    boldText: "happy",
    answerType: 'radios',
    radioOptions: ['Never', 'Rarely', 'Regularly', 'Every day'],
    },
  46: {
    questionId: 46,
    questionText: 'Thank you for sharing how you feel. Almost finished…',
    answerType: 'radios',
    radioOptions: [],
    },
  47: {
    questionId: 47,
    questionText: 'I had a lot of contact with my friends and family at home',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  48: {
    questionId: 48,
    questionText: 'Going ashore gave me new energy',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  49: {
    questionId: 49,
    questionText: 'It was nice to have internet access',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  50: {
    questionId: 50,
    questionText: 'I drank too much alcohol',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  51: {
    questionId: 51,
    questionText: 'I spent most of my free time on the ship',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  52: {
    questionId: 52,
    questionText: 'I made new friends',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  53: {
    questionId: 53,
    questionText: 'I didn\'t want to go back at sea',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  54: {
    questionId: 54,
    questionText: 'I feel frustrated with my coach',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  55: {
    questionId: 55,
    questionText: 'I am relieved it is almost over',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  56: {
    questionId: 56,
    questionText: 'I am happy with the things I learned',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  57: {
    questionId: 57,
    questionText: 'In my free time, I usually sit by myself',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  58: {
    questionId: 58,
    questionText: 'The atmosphere between students is positive',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  59: {
    questionId: 59,
    questionText: 'I feel bored and frustrated',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  60: {
    questionId: 60,
    questionText: 'I participated in fun social activities',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
     },
  61: {
    questionId: 61,
    questionText: 'During the past week, I have been feeling ',
    boldText: "satisfied",
    answerType: 'radios',
    radioOptions: ['Never', 'Rarely', 'Regularly', 'Every day'],
    },
  62: {
    questionId: 62,
    questionText: 'I feel confident about pursuing a maritime career',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  63: {
    questionId: 63,
    questionText: 'I helped others in need',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  64: {
    questionId: 64,
    questionText: 'I will miss being at sea',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  65: {
    questionId: 65,
    questionText: 'I feel I have created meaningful relationships',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  66: {
    questionId: 66,
    questionText: 'Being far away from home has been very difficult',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  67: {
    questionId: 67,
    questionText: 'I feel confident to achieve my goals',
    answerType: 'radios',
    radioOptions: ['Strongly disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly agree'],
    },
  68: {
    questionId: 68,
    questionText: 'Merci de votre participation! Afin de conclure correctement cette enquête, nous vous demandons d\'exporter les données, même si vous n\'avez rien rempli ou très peu. \n\nBedankt voor je deelname! Om dit experiment correct af te sluiten, vragen we je de data te exporteren, ook al heb je weinig of niets ingevuld! \n\nEnjoy your time at home :)',
    answerType: 'radios',
    radioOptions: [],
    },
  69: {
    questionId: 69,
    questionText: 'Thank you for sharing how you feel ! Just a few more items about your shore leave…',
    answerType: 'radios',
    radioOptions: [],
    },
  70: {
    questionId: 70,
    questionText: 'During the past week, I have been feeling ',
    boldText: "insecure",
    answerType: 'radios',
    radioOptions: ['Never', 'Rarely', 'Regularly', 'Every day'],
    },
  71: {
    questionId: 71,
    questionText: 'My gender is',
    answerType: 'radios',
    radioOptions: ['Female', 'Male', 'Other'],
    },
  72: {
    questionId: 72,
    questionText: 'I am part of team',
    answerType: 'radios',
    radioOptions: ['IA','IB','IC','IIA','IIB','IIC','IIIA','IIIB','IIIC'],
    },
  73: {
    questionId: 73,
    questionText: 'I am in department',
    answerType: 'radios',
    radioOptions: ['NW', 'SN', 'SW', 'MN'],
    },
  74: {
    questionId: 74,
    questionText: 'I am a',
    answerType: 'radios',
    radioOptions: ['Coach', 'Student'],
    },
  }
    